id: PA66B86AD
initial_creation_type: ocr
source_metadata:
  volumes:
    be51e60e24b84b0f8e4eabe2bd8a2558:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ''
      total_pages: 1872
      volume_number: 114
