id: D1FCF38F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:14:13+00:00'
last_modified: '2022-05-30T07:53:16.505305+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '3443':
      image_group_id: I1PD95959
      title: ''
      total_pages: 1872
      order: 114
      base_file: 3443.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
